# Light: Catppuccin Latte / Dark: Catppuccin Mocha

GHOSTTY_LIGHT="Catppuccin Latte"
GHOSTTY_DARK="Catppuccin Mocha"

NVIM_LIGHT="catppuccin-latte"
NVIM_DARK="catppuccin-mocha"

YAZI_LIGHT="catppuccin-latte"
YAZI_DARK="catppuccin-mocha"

TMUX_LIGHT_ACTIVE="#1e66f5"
TMUX_LIGHT_ACCENT="#1e66f5"
TMUX_LIGHT_TEXT="#4c4f69"
TMUX_LIGHT_PILL_TEXT="#eff1f5"
TMUX_LIGHT_INACTIVE="#9ca0b0"

TMUX_DARK_ACTIVE="#89b4fa"
TMUX_DARK_ACCENT="#89b4fa"
TMUX_DARK_TEXT="#cdd6f4"
TMUX_DARK_PILL_TEXT="colour231"
TMUX_DARK_INACTIVE="#6c7086"
