# Light: Catppuccin Latte / Dark: TokyoNight

GHOSTTY_LIGHT="Catppuccin Latte"
GHOSTTY_DARK="TokyoNight Storm"

NVIM_LIGHT="catppuccin-latte"
NVIM_DARK="tokyonight-moon"

YAZI_LIGHT="catppuccin-latte"
YAZI_DARK="tokyo-night"

TMUX_LIGHT_ACTIVE="#1e66f5"
TMUX_LIGHT_ACCENT="#1e66f5"
TMUX_LIGHT_TEXT="#4c4f69"
TMUX_LIGHT_PILL_TEXT="#eff1f5"
TMUX_LIGHT_INACTIVE="#9ca0b0"

TMUX_DARK_ACTIVE="#82aaff"
TMUX_DARK_ACCENT="#82aaff"
TMUX_DARK_TEXT="#c8d3f5"
TMUX_DARK_PILL_TEXT="colour231"
TMUX_DARK_INACTIVE="colour24"
